//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./GraphicAPIProxy_types');
//HELPER FUNCTIONS AND STRUCTURES

GraphicAPIProxy_getUndirectedGraphic4Knowledge_args = function(args) {
  this.keyword = null;
  this.depth = null;
  if (args) {
    if (args.keyword !== undefined) {
      this.keyword = args.keyword;
    }
    if (args.depth !== undefined) {
      this.depth = args.depth;
    }
  }
};
GraphicAPIProxy_getUndirectedGraphic4Knowledge_args.prototype = {};
GraphicAPIProxy_getUndirectedGraphic4Knowledge_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.keyword = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.depth = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Knowledge_args.prototype.write = function(output) {
  output.writeStructBegin('GraphicAPIProxy_getUndirectedGraphic4Knowledge_args');
  if (this.keyword !== null && this.keyword !== undefined) {
    output.writeFieldBegin('keyword', Thrift.Type.STRING, 1);
    output.writeString(this.keyword);
    output.writeFieldEnd();
  }
  if (this.depth !== null && this.depth !== undefined) {
    output.writeFieldBegin('depth', Thrift.Type.I32, 2);
    output.writeI32(this.depth);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Knowledge_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GraphicAPIProxy_getUndirectedGraphic4Knowledge_result.prototype = {};
GraphicAPIProxy_getUndirectedGraphic4Knowledge_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Knowledge_result.prototype.write = function(output) {
  output.writeStructBegin('GraphicAPIProxy_getUndirectedGraphic4Knowledge_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Expert_args = function(args) {
  this.name = null;
  this.depth = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.depth !== undefined) {
      this.depth = args.depth;
    }
  }
};
GraphicAPIProxy_getUndirectedGraphic4Expert_args.prototype = {};
GraphicAPIProxy_getUndirectedGraphic4Expert_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.depth = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Expert_args.prototype.write = function(output) {
  output.writeStructBegin('GraphicAPIProxy_getUndirectedGraphic4Expert_args');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.depth !== null && this.depth !== undefined) {
    output.writeFieldBegin('depth', Thrift.Type.I32, 2);
    output.writeI32(this.depth);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Expert_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GraphicAPIProxy_getUndirectedGraphic4Expert_result.prototype = {};
GraphicAPIProxy_getUndirectedGraphic4Expert_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GraphicAPIProxy_getUndirectedGraphic4Expert_result.prototype.write = function(output) {
  output.writeStructBegin('GraphicAPIProxy_getUndirectedGraphic4Expert_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GraphicAPIProxyClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
GraphicAPIProxyClient.prototype = {};
GraphicAPIProxyClient.prototype.seqid = function() { return this._seqid; }
GraphicAPIProxyClient.prototype.new_seqid = function() { return this._seqid += 1; }
GraphicAPIProxyClient.prototype.getUndirectedGraphic4Knowledge = function(keyword, depth, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getUndirectedGraphic4Knowledge(keyword, depth);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getUndirectedGraphic4Knowledge(keyword, depth);
  }
};

GraphicAPIProxyClient.prototype.send_getUndirectedGraphic4Knowledge = function(keyword, depth) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getUndirectedGraphic4Knowledge', Thrift.MessageType.CALL, this.seqid());
  var args = new GraphicAPIProxy_getUndirectedGraphic4Knowledge_args();
  args.keyword = keyword;
  args.depth = depth;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GraphicAPIProxyClient.prototype.recv_getUndirectedGraphic4Knowledge = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GraphicAPIProxy_getUndirectedGraphic4Knowledge_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getUndirectedGraphic4Knowledge failed: unknown result');
};
GraphicAPIProxyClient.prototype.getUndirectedGraphic4Expert = function(name, depth, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getUndirectedGraphic4Expert(name, depth);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getUndirectedGraphic4Expert(name, depth);
  }
};

GraphicAPIProxyClient.prototype.send_getUndirectedGraphic4Expert = function(name, depth) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getUndirectedGraphic4Expert', Thrift.MessageType.CALL, this.seqid());
  var args = new GraphicAPIProxy_getUndirectedGraphic4Expert_args();
  args.name = name;
  args.depth = depth;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

GraphicAPIProxyClient.prototype.recv_getUndirectedGraphic4Expert = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new GraphicAPIProxy_getUndirectedGraphic4Expert_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getUndirectedGraphic4Expert failed: unknown result');
};
GraphicAPIProxyProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
GraphicAPIProxyProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

GraphicAPIProxyProcessor.prototype.process_getUndirectedGraphic4Knowledge = function(seqid, input, output) {
  var args = new GraphicAPIProxy_getUndirectedGraphic4Knowledge_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getUndirectedGraphic4Knowledge.length === 2) {
    Q.fcall(this._handler.getUndirectedGraphic4Knowledge, args.keyword, args.depth)
      .then(function(result) {
        var result = new GraphicAPIProxy_getUndirectedGraphic4Knowledge_result({success: result});
        output.writeMessageBegin("getUndirectedGraphic4Knowledge", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUndirectedGraphic4Knowledge", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getUndirectedGraphic4Knowledge(args.keyword, args.depth, function (err, result) {
      if (err == null) {
        var result = new GraphicAPIProxy_getUndirectedGraphic4Knowledge_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getUndirectedGraphic4Knowledge", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUndirectedGraphic4Knowledge", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

GraphicAPIProxyProcessor.prototype.process_getUndirectedGraphic4Expert = function(seqid, input, output) {
  var args = new GraphicAPIProxy_getUndirectedGraphic4Expert_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getUndirectedGraphic4Expert.length === 2) {
    Q.fcall(this._handler.getUndirectedGraphic4Expert, args.name, args.depth)
      .then(function(result) {
        var result = new GraphicAPIProxy_getUndirectedGraphic4Expert_result({success: result});
        output.writeMessageBegin("getUndirectedGraphic4Expert", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUndirectedGraphic4Expert", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getUndirectedGraphic4Expert(args.name, args.depth, function (err, result) {
      if (err == null) {
        var result = new GraphicAPIProxy_getUndirectedGraphic4Expert_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getUndirectedGraphic4Expert", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getUndirectedGraphic4Expert", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

